"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class plan_control_t(object):
    __slots__ = ["utime", "control"]

    PAUSE = 0
    UNPAUSE = 1
    TERMINATE = 2
    REVERT = 3

    def __init__(self):
        self.utime = 0
        self.control = 0

    def encode(self):
        buf = BytesIO()
        buf.write(plan_control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.utime, self.control))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != plan_control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return plan_control_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = plan_control_t()
        self.utime, self.control = struct.unpack(">qh", buf.read(10))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if plan_control_t in parents: return 0
        tmphash = (0xea36ce2aa3db0564) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if plan_control_t._packed_fingerprint is None:
            plan_control_t._packed_fingerprint = struct.pack(">Q", plan_control_t._get_hash_recursive([]))
        return plan_control_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

