"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_joint_pd_override(object):
    __slots__ = ["timestamp", "position_ind", "qi_des", "qdi_des", "kp", "kd", "weight"]

    def __init__(self):
        self.timestamp = 0
        self.position_ind = 0
        self.qi_des = 0.0
        self.qdi_des = 0.0
        self.kp = 0.0
        self.kd = 0.0
        self.weight = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_joint_pd_override._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiddddd", self.timestamp, self.position_ind, self.qi_des, self.qdi_des, self.kp, self.kd, self.weight))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_joint_pd_override._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_joint_pd_override._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_joint_pd_override()
        self.timestamp, self.position_ind, self.qi_des, self.qdi_des, self.kp, self.kd, self.weight = struct.unpack(">qiddddd", buf.read(52))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_joint_pd_override in parents: return 0
        tmphash = (0xb4fc4aa2b64a2627) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_joint_pd_override._packed_fingerprint is None:
            lcmt_joint_pd_override._packed_fingerprint = struct.pack(">Q", lcmt_joint_pd_override._get_hash_recursive([]))
        return lcmt_joint_pd_override._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

