"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_quadrotor_input_t(object):
    __slots__ = ["timestamp", "motors"]

    def __init__(self):
        self.timestamp = 0
        self.motors = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_quadrotor_input_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>4d', *self.motors[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_quadrotor_input_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_quadrotor_input_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_quadrotor_input_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.motors = struct.unpack('>4d', buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_quadrotor_input_t in parents: return 0
        tmphash = (0x9ae6ebfcdee0c3b7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_quadrotor_input_t._packed_fingerprint is None:
            lcmt_quadrotor_input_t._packed_fingerprint = struct.pack(">Q", lcmt_quadrotor_input_t._get_hash_recursive([]))
        return lcmt_quadrotor_input_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

