"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_foot_flag(object):
    __slots__ = ["timestamp", "right", "left"]

    def __init__(self):
        self.timestamp = 0
        self.right = False
        self.left = False

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_foot_flag._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbb", self.timestamp, self.right, self.left))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_foot_flag._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_foot_flag._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_foot_flag()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.right = bool(struct.unpack('b', buf.read(1))[0])
        self.left = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_foot_flag in parents: return 0
        tmphash = (0x7298c99b6c147dc2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_foot_flag._packed_fingerprint is None:
            lcmt_foot_flag._packed_fingerprint = struct.pack(">Q", lcmt_foot_flag._get_hash_recursive([]))
        return lcmt_foot_flag._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

