"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import drake.lcmt_constrained_values

class lcmt_desired_dof_motions(object):
    __slots__ = ["timestamp", "num_dof", "dof_names", "constrained_accelerations"]

    def __init__(self):
        self.timestamp = 0
        self.num_dof = 0
        self.dof_names = []
        self.constrained_accelerations = drake.lcmt_constrained_values()

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_desired_dof_motions._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.num_dof))
        for i0 in range(self.num_dof):
            __dof_names_encoded = self.dof_names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__dof_names_encoded)+1))
            buf.write(__dof_names_encoded)
            buf.write(b"\0")
        assert self.constrained_accelerations._get_packed_fingerprint() == drake.lcmt_constrained_values._get_packed_fingerprint()
        self.constrained_accelerations._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_desired_dof_motions._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_desired_dof_motions._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_desired_dof_motions()
        self.timestamp, self.num_dof = struct.unpack(">qi", buf.read(12))
        self.dof_names = []
        for i0 in range(self.num_dof):
            __dof_names_len = struct.unpack('>I', buf.read(4))[0]
            self.dof_names.append(buf.read(__dof_names_len)[:-1].decode('utf-8', 'replace'))
        self.constrained_accelerations = drake.lcmt_constrained_values._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_desired_dof_motions in parents: return 0
        newparents = parents + [lcmt_desired_dof_motions]
        tmphash = (0xf6cbc71b90c98dc5+ drake.lcmt_constrained_values._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_desired_dof_motions._packed_fingerprint is None:
            lcmt_desired_dof_motions._packed_fingerprint = struct.pack(">Q", lcmt_desired_dof_motions._get_hash_recursive([]))
        return lcmt_desired_dof_motions._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

