"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_simple_car_config_t(object):
    __slots__ = ["timestamp", "wheelbase", "track", "max_abs_steering_angle", "max_velocity", "max_acceleration", "velocity_lookahead_time", "velocity_kp"]

    def __init__(self):
        self.timestamp = 0
        self.wheelbase = 0.0
        self.track = 0.0
        self.max_abs_steering_angle = 0.0
        self.max_velocity = 0.0
        self.max_acceleration = 0.0
        self.velocity_lookahead_time = 0.0
        self.velocity_kp = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_simple_car_config_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddddddd", self.timestamp, self.wheelbase, self.track, self.max_abs_steering_angle, self.max_velocity, self.max_acceleration, self.velocity_lookahead_time, self.velocity_kp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_simple_car_config_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_simple_car_config_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_simple_car_config_t()
        self.timestamp, self.wheelbase, self.track, self.max_abs_steering_angle, self.max_velocity, self.max_acceleration, self.velocity_lookahead_time, self.velocity_kp = struct.unpack(">qddddddd", buf.read(64))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_simple_car_config_t in parents: return 0
        tmphash = (0xe31af7c58a9625df) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_simple_car_config_t._packed_fingerprint is None:
            lcmt_simple_car_config_t._packed_fingerprint = struct.pack(">Q", lcmt_simple_car_config_t._get_hash_recursive([]))
        return lcmt_simple_car_config_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

