"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_simple_car_state_t(object):
    __slots__ = ["timestamp", "x", "y", "heading", "velocity"]

    def __init__(self):
        self.timestamp = 0
        self.x = 0.0
        self.y = 0.0
        self.heading = 0.0
        self.velocity = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_simple_car_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddd", self.timestamp, self.x, self.y, self.heading, self.velocity))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_simple_car_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_simple_car_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_simple_car_state_t()
        self.timestamp, self.x, self.y, self.heading, self.velocity = struct.unpack(">qdddd", buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_simple_car_state_t in parents: return 0
        tmphash = (0xa63c6521c83524c3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_simple_car_state_t._packed_fingerprint is None:
            lcmt_simple_car_state_t._packed_fingerprint = struct.pack(">Q", lcmt_simple_car_state_t._get_hash_recursive([]))
        return lcmt_simple_car_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

