"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import drake.lcmt_constrained_values

class lcmt_desired_centroidal_momentum_dot(object):
    __slots__ = ["timestamp", "centroidal_momentum_dot"]

    def __init__(self):
        self.timestamp = 0
        self.centroidal_momentum_dot = drake.lcmt_constrained_values()

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_desired_centroidal_momentum_dot._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        assert self.centroidal_momentum_dot._get_packed_fingerprint() == drake.lcmt_constrained_values._get_packed_fingerprint()
        self.centroidal_momentum_dot._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_desired_centroidal_momentum_dot._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_desired_centroidal_momentum_dot._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_desired_centroidal_momentum_dot()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.centroidal_momentum_dot = drake.lcmt_constrained_values._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_desired_centroidal_momentum_dot in parents: return 0
        newparents = parents + [lcmt_desired_centroidal_momentum_dot]
        tmphash = (0x49fa7e8e82ec9b1b+ drake.lcmt_constrained_values._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_desired_centroidal_momentum_dot._packed_fingerprint is None:
            lcmt_desired_centroidal_momentum_dot._packed_fingerprint = struct.pack(">Q", lcmt_desired_centroidal_momentum_dot._get_hash_recursive([]))
        return lcmt_desired_centroidal_momentum_dot._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

