"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_body_wrench_data(object):
    __slots__ = ["timestamp", "body_name", "wrench"]

    def __init__(self):
        self.timestamp = 0
        self.body_name = ""
        self.wrench = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_body_wrench_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __body_name_encoded = self.body_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__body_name_encoded)+1))
        buf.write(__body_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>6d', *self.wrench[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_body_wrench_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_body_wrench_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_body_wrench_data()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __body_name_len = struct.unpack('>I', buf.read(4))[0]
        self.body_name = buf.read(__body_name_len)[:-1].decode('utf-8', 'replace')
        self.wrench = struct.unpack('>6d', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_body_wrench_data in parents: return 0
        tmphash = (0x4f915c221730709e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_body_wrench_data._packed_fingerprint is None:
            lcmt_body_wrench_data._packed_fingerprint = struct.pack(">Q", lcmt_body_wrench_data._get_hash_recursive([]))
        return lcmt_body_wrench_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

