"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import bot_core.gps_satellite_info_t

class gps_satellite_info_list_t(object):
    __slots__ = ["utime", "num_sats", "sat_info"]

    def __init__(self):
        self.utime = 0
        self.num_sats = 0
        self.sat_info = []

    def encode(self):
        buf = BytesIO()
        buf.write(gps_satellite_info_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_sats))
        for i0 in range(self.num_sats):
            assert self.sat_info[i0]._get_packed_fingerprint() == bot_core.gps_satellite_info_t._get_packed_fingerprint()
            self.sat_info[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps_satellite_info_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps_satellite_info_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gps_satellite_info_list_t()
        self.utime, self.num_sats = struct.unpack(">qi", buf.read(12))
        self.sat_info = []
        for i0 in range(self.num_sats):
            self.sat_info.append(bot_core.gps_satellite_info_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gps_satellite_info_list_t in parents: return 0
        newparents = parents + [gps_satellite_info_list_t]
        tmphash = (0x1f4e7c464d4ad1e4+ bot_core.gps_satellite_info_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gps_satellite_info_list_t._packed_fingerprint is None:
            gps_satellite_info_list_t._packed_fingerprint = struct.pack(">Q", gps_satellite_info_list_t._get_hash_recursive([]))
        return gps_satellite_info_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

