"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class kvh_raw_imu_t(object):
    __slots__ = ["utime", "packet_count", "delta_rotation", "linear_acceleration"]

    def __init__(self):
        self.utime = 0
        self.packet_count = 0
        self.delta_rotation = [ 0.0 for dim0 in range(3) ]
        self.linear_acceleration = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(kvh_raw_imu_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.utime, self.packet_count))
        buf.write(struct.pack('>3d', *self.delta_rotation[:3]))
        buf.write(struct.pack('>3d', *self.linear_acceleration[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != kvh_raw_imu_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return kvh_raw_imu_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = kvh_raw_imu_t()
        self.utime, self.packet_count = struct.unpack(">qq", buf.read(16))
        self.delta_rotation = struct.unpack('>3d', buf.read(24))
        self.linear_acceleration = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if kvh_raw_imu_t in parents: return 0
        tmphash = (0x90eec8e5d8bdd893) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if kvh_raw_imu_t._packed_fingerprint is None:
            kvh_raw_imu_t._packed_fingerprint = struct.pack(">Q", kvh_raw_imu_t._get_hash_recursive([]))
        return kvh_raw_imu_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

