"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rigid_transform_t(object):
    __slots__ = ["utime", "trans", "quat"]

    def __init__(self):
        self.utime = 0
        self.trans = [ 0.0 for dim0 in range(3) ]
        self.quat = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(rigid_transform_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3d', *self.trans[:3]))
        buf.write(struct.pack('>4d', *self.quat[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rigid_transform_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rigid_transform_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rigid_transform_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.trans = struct.unpack('>3d', buf.read(24))
        self.quat = struct.unpack('>4d', buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if rigid_transform_t in parents: return 0
        tmphash = (0x754ffdf95662e2d7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rigid_transform_t._packed_fingerprint is None:
            rigid_transform_t._packed_fingerprint = struct.pack(">Q", rigid_transform_t._get_hash_recursive([]))
        return rigid_transform_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

