"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sensor_status_t(object):
    __slots__ = ["utime", "sensor_name", "rate", "type"]

    VELODYNE_32 = 0
    VELODYNE_64 = 1
    SICK_LASER = 2
    HOKUYO_LASER = 3
    KINECT = 4
    IMU = 5
    ORC = 6
    DYNAMIXEL_SERVO = 7

    def __init__(self):
        self.utime = 0
        self.sensor_name = ""
        self.rate = 0.0
        self.type = 0

    def encode(self):
        buf = BytesIO()
        buf.write(sensor_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __sensor_name_encoded = self.sensor_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__sensor_name_encoded)+1))
        buf.write(__sensor_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">dh", self.rate, self.type))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sensor_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sensor_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sensor_status_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __sensor_name_len = struct.unpack('>I', buf.read(4))[0]
        self.sensor_name = buf.read(__sensor_name_len)[:-1].decode('utf-8', 'replace')
        self.rate, self.type = struct.unpack(">dh", buf.read(10))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sensor_status_t in parents: return 0
        tmphash = (0x915ec758cf41a556) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sensor_status_t._packed_fingerprint is None:
            sensor_status_t._packed_fingerprint = struct.pack(">Q", sensor_status_t._get_hash_recursive([]))
        return sensor_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

