"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class six_axis_force_torque_t(object):
    __slots__ = ["utime", "force", "moment"]

    def __init__(self):
        self.utime = 0
        self.force = [ 0.0 for dim0 in range(3) ]
        self.moment = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(six_axis_force_torque_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3d', *self.force[:3]))
        buf.write(struct.pack('>3d', *self.moment[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != six_axis_force_torque_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return six_axis_force_torque_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = six_axis_force_torque_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.force = struct.unpack('>3d', buf.read(24))
        self.moment = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if six_axis_force_torque_t in parents: return 0
        tmphash = (0x7b83c832c5751c76) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if six_axis_force_torque_t._packed_fingerprint is None:
            six_axis_force_torque_t._packed_fingerprint = struct.pack(">Q", six_axis_force_torque_t._get_hash_recursive([]))
        return six_axis_force_torque_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

