"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import bot_core.six_axis_force_torque_t

class six_axis_force_torque_array_t(object):
    __slots__ = ["utime", "num_sensors", "names", "sensors"]

    def __init__(self):
        self.utime = 0
        self.num_sensors = 0
        self.names = []
        self.sensors = []

    def encode(self):
        buf = BytesIO()
        buf.write(six_axis_force_torque_array_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_sensors))
        for i0 in range(self.num_sensors):
            __names_encoded = self.names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__names_encoded)+1))
            buf.write(__names_encoded)
            buf.write(b"\0")
        for i0 in range(self.num_sensors):
            assert self.sensors[i0]._get_packed_fingerprint() == bot_core.six_axis_force_torque_t._get_packed_fingerprint()
            self.sensors[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != six_axis_force_torque_array_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return six_axis_force_torque_array_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = six_axis_force_torque_array_t()
        self.utime, self.num_sensors = struct.unpack(">qi", buf.read(12))
        self.names = []
        for i0 in range(self.num_sensors):
            __names_len = struct.unpack('>I', buf.read(4))[0]
            self.names.append(buf.read(__names_len)[:-1].decode('utf-8', 'replace'))
        self.sensors = []
        for i0 in range(self.num_sensors):
            self.sensors.append(bot_core.six_axis_force_torque_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if six_axis_force_torque_array_t in parents: return 0
        newparents = parents + [six_axis_force_torque_array_t]
        tmphash = (0x65249446b17c2368+ bot_core.six_axis_force_torque_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if six_axis_force_torque_array_t._packed_fingerprint is None:
            six_axis_force_torque_array_t._packed_fingerprint = struct.pack(">Q", six_axis_force_torque_array_t._get_hash_recursive([]))
        return six_axis_force_torque_array_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

