"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class request_t(object):
    __slots__ = ["utime"]

    def __init__(self):
        self.utime = 0

    def encode(self):
        buf = BytesIO()
        buf.write(request_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != request_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return request_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = request_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if request_t in parents: return 0
        tmphash = (0xa686a0e0f882d897) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if request_t._packed_fingerprint is None:
            request_t._packed_fingerprint = struct.pack(">Q", request_t._get_hash_recursive([]))
        return request_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

