// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>
#include "drake_lcmtypes_export.h"

#ifndef _drake_lcmt_piecewise_polynomial_h
#define _drake_lcmt_piecewise_polynomial_h

#ifdef __cplusplus
extern "C" {
#endif

#include "drake_lcmt_polynomial_matrix.h"
typedef struct _drake_lcmt_piecewise_polynomial drake_lcmt_piecewise_polynomial;
struct _drake_lcmt_piecewise_polynomial
{
    int64_t    timestamp;
    int32_t    num_breaks;
    double     *breaks;
    int32_t    num_segments;
    drake_lcmt_polynomial_matrix *polynomial_matrices;
};

/**
 * Create a deep copy of a drake_lcmt_piecewise_polynomial.
 * When no longer needed, destroy it with drake_lcmt_piecewise_polynomial_destroy()
 */
DRAKE_LCMTYPES_EXPORT drake_lcmt_piecewise_polynomial* drake_lcmt_piecewise_polynomial_copy(const drake_lcmt_piecewise_polynomial* to_copy);

/**
 * Destroy an instance of drake_lcmt_piecewise_polynomial created by drake_lcmt_piecewise_polynomial_copy()
 */
DRAKE_LCMTYPES_EXPORT void drake_lcmt_piecewise_polynomial_destroy(drake_lcmt_piecewise_polynomial* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _drake_lcmt_piecewise_polynomial_subscription_t drake_lcmt_piecewise_polynomial_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * drake_lcmt_piecewise_polynomial is received.
 */
typedef void(*drake_lcmt_piecewise_polynomial_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const drake_lcmt_piecewise_polynomial *msg, void *userdata);

/**
 * Publish a message of type drake_lcmt_piecewise_polynomial using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
DRAKE_LCMTYPES_EXPORT int drake_lcmt_piecewise_polynomial_publish(lcm_t *lcm, const char *channel, const drake_lcmt_piecewise_polynomial *msg);

/**
 * Subscribe to messages of type drake_lcmt_piecewise_polynomial using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
DRAKE_LCMTYPES_EXPORT drake_lcmt_piecewise_polynomial_subscription_t* drake_lcmt_piecewise_polynomial_subscribe(lcm_t *lcm, const char *channel, drake_lcmt_piecewise_polynomial_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by drake_lcmt_piecewise_polynomial_subscribe()
 */
DRAKE_LCMTYPES_EXPORT int drake_lcmt_piecewise_polynomial_unsubscribe(lcm_t *lcm, drake_lcmt_piecewise_polynomial_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
DRAKE_LCMTYPES_EXPORT int drake_lcmt_piecewise_polynomial_subscription_set_queue_capacity(drake_lcmt_piecewise_polynomial_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type drake_lcmt_piecewise_polynomial into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to drake_lcmt_piecewise_polynomial_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
DRAKE_LCMTYPES_EXPORT int drake_lcmt_piecewise_polynomial_encode(void *buf, int offset, int maxlen, const drake_lcmt_piecewise_polynomial *p);

/**
 * Decode a message of type drake_lcmt_piecewise_polynomial from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with drake_lcmt_piecewise_polynomial_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
DRAKE_LCMTYPES_EXPORT int drake_lcmt_piecewise_polynomial_decode(const void *buf, int offset, int maxlen, drake_lcmt_piecewise_polynomial *msg);

/**
 * Release resources allocated by drake_lcmt_piecewise_polynomial_decode()
 * @return 0
 */
DRAKE_LCMTYPES_EXPORT int drake_lcmt_piecewise_polynomial_decode_cleanup(drake_lcmt_piecewise_polynomial *p);

/**
 * Check how many bytes are required to encode a message of type drake_lcmt_piecewise_polynomial
 */
DRAKE_LCMTYPES_EXPORT int drake_lcmt_piecewise_polynomial_encoded_size(const drake_lcmt_piecewise_polynomial *p);

// LCM support functions. Users should not call these
DRAKE_LCMTYPES_EXPORT int64_t __drake_lcmt_piecewise_polynomial_get_hash(void);
DRAKE_LCMTYPES_EXPORT uint64_t __drake_lcmt_piecewise_polynomial_hash_recursive(const __lcm_hash_ptr *p);
DRAKE_LCMTYPES_EXPORT int __drake_lcmt_piecewise_polynomial_encode_array(void *buf, int offset, int maxlen, const drake_lcmt_piecewise_polynomial *p, int elements);
DRAKE_LCMTYPES_EXPORT int __drake_lcmt_piecewise_polynomial_decode_array(const void *buf, int offset, int maxlen, drake_lcmt_piecewise_polynomial *p, int elements);
DRAKE_LCMTYPES_EXPORT int __drake_lcmt_piecewise_polynomial_decode_array_cleanup(drake_lcmt_piecewise_polynomial *p, int elements);
DRAKE_LCMTYPES_EXPORT int __drake_lcmt_piecewise_polynomial_encoded_array_size(const drake_lcmt_piecewise_polynomial *p, int elements);
DRAKE_LCMTYPES_EXPORT int __drake_lcmt_piecewise_polynomial_clone_array(const drake_lcmt_piecewise_polynomial *p, drake_lcmt_piecewise_polynomial *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
