
#ifndef ROBOTLOCOMOTION_LCMTYPES_EXPORT_H
#define ROBOTLOCOMOTION_LCMTYPES_EXPORT_H

#ifdef ROBOTLOCOMOTION_LCMTYPES_STATIC_DEFINE
#  define ROBOTLOCOMOTION_LCMTYPES_EXPORT
#  define ROBOTLOCOMOTION_LCMTYPES_NO_EXPORT
#else
#  ifndef ROBOTLOCOMOTION_LCMTYPES_EXPORT
#    ifdef robotlocomotion_lcmtypes_EXPORTS
        /* We are building this library */
#      define ROBOTLOCOMOTION_LCMTYPES_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define ROBOTLOCOMOTION_LCMTYPES_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef ROBOTLOCOMOTION_LCMTYPES_NO_EXPORT
#    define ROBOTLOCOMOTION_LCMTYPES_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef ROBOTLOCOMOTION_LCMTYPES_DEPRECATED
#  define ROBOTLOCOMOTION_LCMTYPES_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef ROBOTLOCOMOTION_LCMTYPES_DEPRECATED_EXPORT
#  define ROBOTLOCOMOTION_LCMTYPES_DEPRECATED_EXPORT ROBOTLOCOMOTION_LCMTYPES_EXPORT ROBOTLOCOMOTION_LCMTYPES_DEPRECATED
#endif

#ifndef ROBOTLOCOMOTION_LCMTYPES_DEPRECATED_NO_EXPORT
#  define ROBOTLOCOMOTION_LCMTYPES_DEPRECATED_NO_EXPORT ROBOTLOCOMOTION_LCMTYPES_NO_EXPORT ROBOTLOCOMOTION_LCMTYPES_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define ROBOTLOCOMOTION_LCMTYPES_NO_DEPRECATED
#endif

#endif
