// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>
#include "robotlocomotion_lcmtypes_export.h"

#ifndef _robotlocomotion_support_sequence_t_h
#define _robotlocomotion_support_sequence_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "robotlocomotion_support_element_t.h"
typedef struct _robotlocomotion_support_sequence_t robotlocomotion_support_sequence_t;
struct _robotlocomotion_support_sequence_t
{
    int64_t    utime;
    int32_t    num_ts;
    double     *ts;
    robotlocomotion_support_element_t *supports;
};

/**
 * Create a deep copy of a robotlocomotion_support_sequence_t.
 * When no longer needed, destroy it with robotlocomotion_support_sequence_t_destroy()
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT robotlocomotion_support_sequence_t* robotlocomotion_support_sequence_t_copy(const robotlocomotion_support_sequence_t* to_copy);

/**
 * Destroy an instance of robotlocomotion_support_sequence_t created by robotlocomotion_support_sequence_t_copy()
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT void robotlocomotion_support_sequence_t_destroy(robotlocomotion_support_sequence_t* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _robotlocomotion_support_sequence_t_subscription_t robotlocomotion_support_sequence_t_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * robotlocomotion_support_sequence_t is received.
 */
typedef void(*robotlocomotion_support_sequence_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const robotlocomotion_support_sequence_t *msg, void *userdata);

/**
 * Publish a message of type robotlocomotion_support_sequence_t using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT int robotlocomotion_support_sequence_t_publish(lcm_t *lcm, const char *channel, const robotlocomotion_support_sequence_t *msg);

/**
 * Subscribe to messages of type robotlocomotion_support_sequence_t using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT robotlocomotion_support_sequence_t_subscription_t* robotlocomotion_support_sequence_t_subscribe(lcm_t *lcm, const char *channel, robotlocomotion_support_sequence_t_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by robotlocomotion_support_sequence_t_subscribe()
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT int robotlocomotion_support_sequence_t_unsubscribe(lcm_t *lcm, robotlocomotion_support_sequence_t_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT int robotlocomotion_support_sequence_t_subscription_set_queue_capacity(robotlocomotion_support_sequence_t_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type robotlocomotion_support_sequence_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to robotlocomotion_support_sequence_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT int robotlocomotion_support_sequence_t_encode(void *buf, int offset, int maxlen, const robotlocomotion_support_sequence_t *p);

/**
 * Decode a message of type robotlocomotion_support_sequence_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with robotlocomotion_support_sequence_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT int robotlocomotion_support_sequence_t_decode(const void *buf, int offset, int maxlen, robotlocomotion_support_sequence_t *msg);

/**
 * Release resources allocated by robotlocomotion_support_sequence_t_decode()
 * @return 0
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT int robotlocomotion_support_sequence_t_decode_cleanup(robotlocomotion_support_sequence_t *p);

/**
 * Check how many bytes are required to encode a message of type robotlocomotion_support_sequence_t
 */
ROBOTLOCOMOTION_LCMTYPES_EXPORT int robotlocomotion_support_sequence_t_encoded_size(const robotlocomotion_support_sequence_t *p);

// LCM support functions. Users should not call these
ROBOTLOCOMOTION_LCMTYPES_EXPORT int64_t __robotlocomotion_support_sequence_t_get_hash(void);
ROBOTLOCOMOTION_LCMTYPES_EXPORT uint64_t __robotlocomotion_support_sequence_t_hash_recursive(const __lcm_hash_ptr *p);
ROBOTLOCOMOTION_LCMTYPES_EXPORT int __robotlocomotion_support_sequence_t_encode_array(void *buf, int offset, int maxlen, const robotlocomotion_support_sequence_t *p, int elements);
ROBOTLOCOMOTION_LCMTYPES_EXPORT int __robotlocomotion_support_sequence_t_decode_array(const void *buf, int offset, int maxlen, robotlocomotion_support_sequence_t *p, int elements);
ROBOTLOCOMOTION_LCMTYPES_EXPORT int __robotlocomotion_support_sequence_t_decode_array_cleanup(robotlocomotion_support_sequence_t *p, int elements);
ROBOTLOCOMOTION_LCMTYPES_EXPORT int __robotlocomotion_support_sequence_t_encoded_array_size(const robotlocomotion_support_sequence_t *p, int elements);
ROBOTLOCOMOTION_LCMTYPES_EXPORT int __robotlocomotion_support_sequence_t_clone_array(const robotlocomotion_support_sequence_t *p, robotlocomotion_support_sequence_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
