/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __drake_lcmt_support_data_hpp__
#define __drake_lcmt_support_data_hpp__

#include <string>
#include <vector>

namespace drake
{

class lcmt_support_data
{
    public:
        int64_t    timestamp;

        std::string body_name;

        int32_t    num_contact_pts;

        std::vector< std::vector< double > > contact_pts;

        int8_t     support_logic_map[4];

        int8_t     use_support_surface;

        float      support_surface[4];

        double     mu;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "lcmt_support_data"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int lcmt_support_data::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_support_data::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmt_support_data::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t lcmt_support_data::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* lcmt_support_data::getTypeName()
{
    return "lcmt_support_data";
}

int lcmt_support_data::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* body_name_cstr = const_cast<char*>(this->body_name.c_str());
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &body_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_contact_pts, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_contact_pts > 0) {
        for (int a0 = 0; a0 < 3; a0++) {
            tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->contact_pts[a0][0], this->num_contact_pts);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->support_logic_map[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->use_support_surface, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->support_surface[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->mu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_support_data::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __body_name_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__body_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__body_name_len__ > maxlen - pos) return -1;
    this->body_name.assign(((const char*)buf) + offset + pos, __body_name_len__ - 1);
    pos += __body_name_len__;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_contact_pts, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->contact_pts.resize(3);
    for (int a0 = 0; a0 < 3; a0++) {
        if(this->num_contact_pts) {
            this->contact_pts[a0].resize(this->num_contact_pts);
            tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->contact_pts[a0][0], this->num_contact_pts);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->support_logic_map[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->use_support_surface, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->support_surface[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->mu, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_support_data::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += this->body_name.size() + 4 + 1;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += 3 * __double_encoded_array_size(NULL, this->num_contact_pts);
    enc_size += __boolean_encoded_array_size(NULL, 4);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 4);
    enc_size += __double_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t lcmt_support_data::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x3f581e659bea3e57LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
