/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __drake_lcmt_resolved_contact_hpp__
#define __drake_lcmt_resolved_contact_hpp__

#include <string>
#include <vector>

namespace drake
{

class lcmt_resolved_contact
{
    public:
        int64_t    timestamp;

        std::string body_name;

        int32_t    num_basis_per_contact_point;

        int32_t    num_all_basis;

        std::vector< double > basis;

        int32_t    num_contact_points;

        std::vector< std::vector< double > > point_forces;

        std::vector< std::vector< double > > contact_points;

        double     equivalent_wrench[6];

        double     reference_point[3];

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "lcmt_resolved_contact"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int lcmt_resolved_contact::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_resolved_contact::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmt_resolved_contact::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t lcmt_resolved_contact::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* lcmt_resolved_contact::getTypeName()
{
    return "lcmt_resolved_contact";
}

int lcmt_resolved_contact::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* body_name_cstr = const_cast<char*>(this->body_name.c_str());
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &body_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_basis_per_contact_point, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_all_basis, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_all_basis > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->basis[0], this->num_all_basis);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_contact_points, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_contact_points > 0) {
        for (int a0 = 0; a0 < 3; a0++) {
            tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->point_forces[a0][0], this->num_contact_points);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    if(this->num_contact_points > 0) {
        for (int a0 = 0; a0 < 3; a0++) {
            tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->contact_points[a0][0], this->num_contact_points);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->equivalent_wrench[0], 6);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->reference_point[0], 3);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_resolved_contact::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __body_name_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__body_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__body_name_len__ > maxlen - pos) return -1;
    this->body_name.assign(((const char*)buf) + offset + pos, __body_name_len__ - 1);
    pos += __body_name_len__;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_basis_per_contact_point, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_all_basis, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_all_basis) {
        this->basis.resize(this->num_all_basis);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->basis[0], this->num_all_basis);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_contact_points, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->point_forces.resize(3);
    for (int a0 = 0; a0 < 3; a0++) {
        if(this->num_contact_points) {
            this->point_forces[a0].resize(this->num_contact_points);
            tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->point_forces[a0][0], this->num_contact_points);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    this->contact_points.resize(3);
    for (int a0 = 0; a0 < 3; a0++) {
        if(this->num_contact_points) {
            this->contact_points[a0].resize(this->num_contact_points);
            tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->contact_points[a0][0], this->num_contact_points);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->equivalent_wrench[0], 6);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->reference_point[0], 3);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_resolved_contact::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += this->body_name.size() + 4 + 1;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->num_all_basis);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += 3 * __double_encoded_array_size(NULL, this->num_contact_points);
    enc_size += 3 * __double_encoded_array_size(NULL, this->num_contact_points);
    enc_size += __double_encoded_array_size(NULL, 6);
    enc_size += __double_encoded_array_size(NULL, 3);
    return enc_size;
}

uint64_t lcmt_resolved_contact::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xe3953cb707390808LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
