/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __drake_lcmt_constrained_values_hpp__
#define __drake_lcmt_constrained_values_hpp__

#include <vector>

namespace drake
{

class lcmt_constrained_values
{
    public:
        int64_t    timestamp;

        int32_t    size;

        std::vector< int8_t > types;

        std::vector< double > weights;

        std::vector< double > values;

    public:
        // If you're using C++11 and are getting compiler errors saying things like
        // ‘constexpr’ needed for in-class initialization of static data member
        // then re-run lcm-gen with '--cpp-std=c++11' to generate code that is
        // compliant with C++11
        static const int8_t   HARD = -1;
        // If you're using C++11 and are getting compiler errors saying things like
        // ‘constexpr’ needed for in-class initialization of static data member
        // then re-run lcm-gen with '--cpp-std=c++11' to generate code that is
        // compliant with C++11
        static const int8_t   SKIP = 0;
        // If you're using C++11 and are getting compiler errors saying things like
        // ‘constexpr’ needed for in-class initialization of static data member
        // then re-run lcm-gen with '--cpp-std=c++11' to generate code that is
        // compliant with C++11
        static const int8_t   SOFT = 1;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "lcmt_constrained_values"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int lcmt_constrained_values::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_constrained_values::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmt_constrained_values::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t lcmt_constrained_values::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* lcmt_constrained_values::getTypeName()
{
    return "lcmt_constrained_values";
}

int lcmt_constrained_values::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->size > 0) {
        tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->types[0], this->size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->size > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->weights[0], this->size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->size > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->values[0], this->size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int lcmt_constrained_values::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->size) {
        this->types.resize(this->size);
        tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->types[0], this->size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->size) {
        this->weights.resize(this->size);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->weights[0], this->size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->size) {
        this->values.resize(this->size);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->values[0], this->size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int lcmt_constrained_values::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, this->size);
    enc_size += __double_encoded_array_size(NULL, this->size);
    enc_size += __double_encoded_array_size(NULL, this->size);
    return enc_size;
}

uint64_t lcmt_constrained_values::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x5d6cd633aff6a330LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
